language: clojure
lein: lein
jdk:
  - openjdk8
before_script:
  - npm install
  - export PATH="$PATH:$(pwd)/node_modules/karma-cli/bin"
script: lein doo chrome-headless test once
before_deploy:
  - rm -rf resources/public/js/compiled
  - lein cljsbuild once min
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: resources/public
  on:
    branch: travis-ci-deployment
